<?php
/*******************************************************************************************
*   ___  _          ______                     _ _                _                        *
*  / _ \| |         | ___ \                   | (_)              | |              © 2019   *
* / /_\ | | _____  _| |_/ /_ __ __ _ _ __   __| |_ _ __   __ _   | |_ ___  __ _ _ __ ___   *
* |  _  | |/ _ \ \/ / ___ \ '__/ _` | '_ \ / _` | | '_ \ / _` |  | __/ _ \/ _` | '_ ` _ \  *
* | | | | |  __/>  <| |_/ / | | (_| | | | | (_| | | | | | (_| |  | ||  __/ (_| | | | | | | *
* \_| |_/_|\___/_/\_\____/|_|  \__,_|_| |_|\__,_|_|_| |_|\__, |  \___\___|\__,_|_| |_| |_| *
*                                                         __/ |                            *
*                                                        |___/                             *
* ---------------------------------------------------------------------------------------- *
* This is commercial software, only users who have purchased a valid license and  accept   *
* to the terms of the License Agreement can install and use this program.                  *
* ---------------------------------------------------------------------------------------- *
* website: https://cs-cart.alexbranding.com                                                *
*   email: info@alexbranding.com                                                           *
*******************************************************************************************/
$schema = array(
'general' => array(
'position' => 100,
'items' => array(
'show_grid_border' => array(
'is_for_all_devices' => 'Y',
'type' => 'selectbox',
'class' => 'input-big',
'position' => 400,
'value' => 'solid_with_margins',
'variants' => array('none','solid_without_margins','solid_with_margins',),
'value_styles' => array(
'Black.less' => 'solid_without_margins',
'Blue.less' => 'solid_without_margins',
'Brick.less' => 'solid_without_margins',
'Dark_Blue.less' => 'solid_without_margins',
'Dark_Navy.less' => 'solid_without_margins',
'Default.less' => 'solid_without_margins',
'Fiolent.less' => 'solid_without_margins',
'Flame.less' => 'solid_without_margins',
'Gray.less' => 'solid_without_margins',
'Green.less' => 'solid_without_margins',
'Ink.less' => 'solid_without_margins',
'Mint.less' => 'solid_without_margins',
'Original.less' => 'solid_without_margins',
'Powder.less' => 'solid_without_margins',
'Purple.less' => 'solid_without_margins',
'Skyfall.less' => 'solid_without_margins',
'Velvet.less' => 'solid_without_margins',
'White.less' => 'solid_without_margins',
),
),
'use_elements_alignment' => array(
'is_for_all_devices' => 'Y',
'type' => 'selectbox',
'class' => 'input-big',
'position' => 420,
'value' => 'use',
'variants' => array('use','do_not_use',),
'value_styles' => array(
'Black.less' => 'use',
'Blue.less' => 'use',
'Brick.less' => 'use',
'Dark_Blue.less' => 'use',
'Dark_Navy.less' => 'use',
'Default.less' => 'use',
'Fiolent.less' => 'use',
'Flame.less' => 'use',
'Gray.less' => 'use',
'Green.less' => 'use',
'Ink.less' => 'use',
'Mint.less' => 'use',
'Original.less' => 'use',
'Powder.less' => 'use',
'Purple.less' => 'use',
'Skyfall.less' => 'use',
'Velvet.less' => 'use',
'White.less' => 'use',
),
),
'button_style' => array(
'is_for_all_devices' => 'Y',
'type' => 'selectbox',
'class' => 'input-big',
'position' => 450,
'value' => 'use_background',
'variants' => array('use_background','use_border',),
'value_styles' => array(
'Black.less' => 'use_background',
'Blue.less' => 'use_background',
'Brick.less' => 'use_background',
'Dark_Blue.less' => 'use_background',
'Dark_Navy.less' => 'use_background',
'Default.less' => 'use_background',
'Fiolent.less' => 'use_background',
'Flame.less' => 'use_background',
'Gray.less' => 'use_background',
'Green.less' => 'use_background',
'Ink.less' => 'use_background',
'Mint.less' => 'use_background',
'Original.less' => 'use_background',
'Powder.less' => 'use_background',
'Purple.less' => 'use_background',
'Skyfall.less' => 'use_background',
'Velvet.less' => 'use_background',
'White.less' => 'use_background',
),
),
'show_button_shadow' => array(
'is_for_all_devices' => 'Y',
'type' => 'checkbox',
'class' => 'input-big',
'position' => 455,
'value' => 'N',
'value_styles' => array(
'Black.less' => 'N',
'Blue.less' => 'Y',
'Brick.less' => 'Y',
'Dark_Blue.less' => 'Y',
'Dark_Navy.less' => 'v',
'Default.less' => 'Y',
'Fiolent.less' => 'Y',
'Flame.less' => 'Y',
'Gray.less' => 'Y',
'Green.less' => 'Y',
'Ink.less' => 'Y',
'Mint.less' => 'N',
'Original.less' => 'Y',
'Powder.less' => 'Y',
'Purple.less' => 'Y',
'Velvet.less' => 'Y',
'Skyfall.less' => 'Y',
'White.less' => 'N',
),
),
'discount_label_style' => array(
'is_for_all_devices' => 'Y',
'type' => 'selectbox',
'class' => 'input-big',
'position' => 460,
'value' => 'as_drop',
'variants' => array('as_drop','as_circle','as_rectangle'),
'value_styles' => array(
'Black.less' => 'as_drop',
'Blue.less' => 'as_drop',
'Brick.less' => 'as_drop',
'Dark_Blue.less' => 'as_drop',
'Dark_Navy.less' => 'as_drop',
'Default.less' => 'as_drop',
'Fiolent.less' => 'as_drop',
'Flame.less' => 'as_drop',
'Gray.less' => 'as_drop',
'Green.less' => 'as_drop',
'Ink.less' => 'as_drop',
'Mint.less' => 'as_drop',
'Original.less' => 'as_drop',
'Powder.less' => 'as_drop',
'Purple.less' => 'as_drop',
'Skyfall.less' => 'as_drop',
'Velvet.less' => 'as_drop',
'White.less' => 'as_drop',
),
),
'use_rounding' => array(
'is_for_all_devices' => 'Y',
'type' => 'selectbox',
'class' => 'input-big',
'position' => 500,
'value' => 'full',
'variants' => array('do_not_use','little','full',),
'value_styles' => array(
'Black.less' => 'little',
'Blue.less' => 'little',
'Brick.less' => 'little',
'Dark_Blue.less' => 'little',
'Dark_Navy.less' => 'little',
'Default.less' => 'little',
'Fiolent.less' => 'little',
'Flame.less' => 'little',
'Gray.less' => 'little',
'Green.less' => 'little',
'Ink.less' => 'little',
'Mint.less' => 'full',
'Original.less' => 'little',
'Powder.less' => 'little',
'Purple.less' => 'full',
'Skyfall.less' => 'full',
'Velvet.less' => 'little',
'White.less' => 'do_not_use',
),
),
'stars_rating_color' => array(
'is_for_all_devices' => 'Y',
'type' => 'colorpicker',
'position' => 600,
'value' => '#ffc107',
'value_styles' => array(
'Black.less' => '#FF3366',
'Blue.less' => '#ffc107',
'Brick.less' => '#ea5920',
'Dark_Blue.less' => '#ffc107',
'Dark_Navy.less' => '#ffc107',
'Default.less' => '#07c',
'Fiolent.less' => '#f25529',
'Flame.less' => '#be0318',
'Gray.less' => '#ff9800',
'Green.less' => '#43b02a',
'Ink.less' => '#ed1e63',
'Mint.less' => '#ff6457',
'Original.less' => '#00a9aa',
'Powder.less' => '#ff7f66',
'Purple.less' => '#c51162',
'Skyfall.less' => '#e25945',
'Velvet.less' => '#cc9900',
'White.less' => '#a1497e',
),
),
'extend_grid_item_on_hover' => array(
'is_for_all_devices' => 'Y',
'type' => 'checkbox',
'position' => 610,
'value' => 'N',
'value_styles' => array(
'Black.less' => 'N',
'Blue.less' => 'N',
'Brick.less' => 'Y',
'Dark_Blue.less' => 'N',
'Dark_Navy.less' => 'N',
'Default.less' => 'N',
'Fiolent.less' => 'Y',
'Flame.less' => 'N',
'Gray.less' => 'N',
'Green.less' => 'Y',
'Ink.less' => 'N',
'Mint.less' => 'N',
'Original.less' => 'N',
'Powder.less' => 'N',
'Purple.less' => 'N',
'Skyfall.less' => 'N',
'Velvet.less' => 'N',
'White.less' => 'Y',
),
),
'show_animation_for_not_empty_cart' => array(
'is_for_all_devices' => 'Y',
'type' => 'checkbox',
'position' => 620,
'value' => 'Y',
'value_styles' => array(
'Black.less' => 'Y',
'Blue.less' => 'Y',
'Brick.less' => 'Y',
'Dark_Blue.less' => 'Y',
'Dark_Navy.less' => 'Y',
'Default.less' => 'Y',
'Fiolent.less' => 'Y',
'Flame.less' => 'Y',
'Gray.less' => 'Y',
'Green.less' => 'Y',
'Ink.less' => 'Y',
'Mint.less' => 'Y',
'Original.less' => 'Y',
'Powder.less' => 'Y',
'Purple.less' => 'Y',
'Skyfall.less' => 'Y',
'Velvet.less' => 'Y',
'White.less' => 'Y',
),
),
),
),
);
return $schema;